export enum ErrorCode {
  // Session (1xx)
  SESSION_NOT_FOUND    = 'E101',
  SESSION_CORRUPT      = 'E102',
  SESSION_EXPIRED      = 'E103',
  // File (2xx)
  FILE_NOT_FOUND       = 'E201',
  FILE_READ_ERROR      = 'E202',
  FILE_WRITE_ERROR     = 'E203',
  PATH_TRAVERSAL       = 'E204',
  FILE_TOO_LARGE       = 'E205',
  // Config (3xx)
  CONFIG_INVALID       = 'E301',
  CONFIG_MISSING_FIELD = 'E302',
  // Tmux (4xx)
  TMUX_NOT_AVAILABLE   = 'E401',
  TMUX_SESSION_NOT_FOUND = 'E402',
  TMUX_PANE_NOT_FOUND  = 'E403',
  TMUX_COMMAND_FAILED  = 'E404',
  // Compression (5xx)
  COMPRESSION_FAILED   = 'E501',
  // Validation (6xx)
  VALIDATION_FAILED    = 'E601',
  INVALID_FORMAT       = 'E602',
  INVALID_STATUS       = 'E603',
  // Agent (7xx)
  AGENT_NOT_FOUND      = 'E701',
  AGENT_STATE_CORRUPT  = 'E702',
  // Security (8xx)
  PATH_OUTSIDE_WORKSPACE = 'E801',
  INVALID_AGENT_NAME   = 'E802',
  SECRETS_DETECTED     = 'E803',
  CONTENT_TOO_LARGE    = 'E804',
}
