/**
 * JSON Schema for HANDOFF.md frontmatter.
 * Can be exported via `handoff schema` for external tooling.
 */

export const HANDOFF_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://github.com/sahilraut22/Handoff/blob/main/schema/handoff-v2.json',
  title: 'Handoff Context Frontmatter',
  description: 'Schema for the YAML frontmatter in HANDOFF.md files generated by handoff-cli',
  type: 'object',
  required: ['handoff_version', 'session_id', 'created_at', 'working_dir', 'changes'],
  properties: {
    handoff_version: {
      type: 'string',
      description: 'Semantic version of the handoff format',
      pattern: '^\\d+\\.\\d+(\\.\\d+)?$',
    },
    session_id: {
      type: 'string',
      description: 'Unique identifier for this handoff session',
      minLength: 1,
    },
    created_at: {
      type: 'string',
      description: 'ISO 8601 timestamp when the session started',
      format: 'date-time',
    },
    duration: {
      type: 'string',
      description: 'Human-readable session duration (e.g. "2h 30m")',
    },
    working_dir: {
      type: 'string',
      description: 'Absolute path to the project root',
      minLength: 1,
    },
    agent: {
      type: 'string',
      description: 'Name of the agent that generated this handoff',
    },
    changes: {
      type: 'object',
      description: 'Summary counts of file changes this session',
      required: ['modified', 'added', 'deleted'],
      properties: {
        modified: { type: 'integer', minimum: 0 },
        added: { type: 'integer', minimum: 0 },
        deleted: { type: 'integer', minimum: 0 },
      },
      additionalProperties: false,
    },
    compression: {
      type: 'object',
      description: 'Compression metadata (present when --compress was used)',
      required: ['enabled', 'token_budget', 'tokens_used'],
      properties: {
        enabled: { type: 'boolean' },
        token_budget: { type: 'integer', minimum: 0 },
        tokens_used: { type: 'integer', minimum: 0 },
      },
      additionalProperties: false,
    },
    priority_files: {
      type: 'array',
      description: 'Critical/high priority files changed this session',
      items: { type: 'string' },
    },
    decisions_included: {
      type: 'integer',
      description: 'Number of architectural decisions included',
      minimum: 0,
    },
  },
  additionalProperties: false,
} as const;
