import { describe, it, expect } from 'vitest';
import { generateHandoffMarkdown } from '../src/lib/markdown.js';
import { DEFAULT_CONFIG } from '../src/lib/config.js';
import type { HandoffContext, Session } from '../src/types/index.js';

function makeSession(overrides: Partial<Session> = {}): Session {
  return {
    session_id: 'test-session-id',
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(), // 1 hour ago
    working_dir: '/test/project',
    file_hashes: {},
    excluded_patterns: ['node_modules'],
    ...overrides,
  };
}

function makeContext(overrides: Partial<HandoffContext> = {}): HandoffContext {
  return {
    session: makeSession(),
    changes: [],
    include_memory: false,
    config: DEFAULT_CONFIG,
    ...overrides,
  };
}

describe('generateHandoffMarkdown', () => {
  it('includes session info', () => {
    const md = generateHandoffMarkdown(makeContext());
    expect(md).toContain('test-session-id');
    expect(md).toContain('/test/project');
  });

  it('shows no changes message when no changes', () => {
    const md = generateHandoffMarkdown(makeContext({ changes: [] }));
    expect(md).toContain('0 files modified, 0 files added, 0 files deleted');
    expect(md).toContain('No changes detected');
  });

  it('includes message when provided', () => {
    const md = generateHandoffMarkdown(makeContext({ message: 'Custom summary message' }));
    expect(md).toContain('Custom summary message');
  });

  it('renders modified file table', () => {
    const context = makeContext({
      changes: [
        { path: 'src/auth.ts', type: 'modified', linesAdded: 10, linesRemoved: 2 },
      ],
    });
    const md = generateHandoffMarkdown(context);
    expect(md).toContain('src/auth.ts');
    expect(md).toContain('+10 / -2');
  });

  it('renders added and deleted file lists', () => {
    const context = makeContext({
      changes: [
        { path: 'src/new.ts', type: 'added' },
        { path: 'src/old.ts', type: 'deleted' },
      ],
    });
    const md = generateHandoffMarkdown(context);
    expect(md).toContain('src/new.ts');
    expect(md).toContain('src/old.ts');
    expect(md).toContain('New Files');
    expect(md).toContain('Deleted Files');
  });

  it('truncates long diffs', () => {
    const longDiff = Array.from({ length: 100 }, (_, i) => `+line ${i}`).join('\n');
    const context = makeContext({
      changes: [{ path: 'src/big.ts', type: 'modified', diff: longDiff }],
      config: { ...DEFAULT_CONFIG, max_diff_lines: 10 },
    });
    const md = generateHandoffMarkdown(context);
    expect(md).toContain('truncated');
    expect(md).toContain('showing first 10');
  });

  it('includes memory content when include_memory is true', () => {
    const context = makeContext({
      include_memory: true,
      memory_contents: { 'CLAUDE.md': '# Memory\nSome context here.' },
    });
    const md = generateHandoffMarkdown(context);
    expect(md).toContain('Agent Memory');
    expect(md).toContain('CLAUDE.md');
    expect(md).toContain('Some context here.');
  });

  it('marks binary files', () => {
    const context = makeContext({
      changes: [{ path: 'image.png', type: 'modified', isBinary: true }],
    });
    const md = generateHandoffMarkdown(context);
    expect(md).toContain('[binary file]');
  });

  it('includes footer', () => {
    const md = generateHandoffMarkdown(makeContext());
    expect(md).toContain('Generated by handoff');
  });
});
